### ISSUE TITLE
question: Drawing features such as p5js

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/ProofWidgets4#87]
Thanks for creating a great library.

How can I use the current ProofWidget to draw like p5js?
For example, I would like to draw the Mandelbrot set or the Julia set.

**Comment by Vtec234** [comment]
Hi! If you just want a simple widget then you don't really need ProofWidgets4 (this library): you can just use the builtin [user widgets](https://lean-lang.org/lean4/doc/examples/widgets.lean.html) mechanism. User widgets are built on top of React, which begs the question of how to integrate p5.js with React. There is [P5-wrapper/react](https://github.com/P5-wrapper/react), but I couldn't get it to work. Instead, we can use `p5.js` directly, like this:
```lean
@[widget_module]
def P5Widget : Lean.Widget.Module where
  javascript := "
    import * as React from 'react'
    import p5 from 'https://esm.sh/p5'

    function sketch(p5) {
      p5.setup = () => {
        p5.createCanvas(600, 400, p5.WEBGL);
      };
      
      p5.draw = () => {
        p5.background(250);
        p5.normalMaterial();
        p5.push();
        p5.rotateZ(p5.frameCount * 0.01);
        p5.rotateX(p5.frameCount * 0.01);
        p5.rotateY(p5.frameCount * 0.01);
        p5.plane(100);
        p5.pop();
      };
    }

    export default function() {
      React.useEffect(() => {
        new p5(sketch, 'p5sketch')
      }, [])
      return React.createElement('div', { id: 'p5sketch' })
    }
    "
    
#widget P5Widget
```

The above example is not great because it doesn't do any cleanup and uses a global id, but it seems to work as a starting point.

What ProofWidgets would allow you to do on top of this is properly integrate P5 with Lean by writing Lean bindings for it. You could define a `Component P5Props` where `P5Props` contains some description of a sketch. Have a look at the [Recharts component](https://github.com/leanprover-community/ProofWidgets4/blob/26bcae6ebc8507c7ea49b81146aef635881f8356/ProofWidgets/Component/Recharts.lean) for an example of bindings for another JS library.

**Comment by Seasawher** [comment]
Thank you!
